---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    templateLink: 'https://dgstoragewy6psz5nn6eam.blob.core.windows.net/armtemplates/CreateMultipleVMs.json'
    #paramsLink: 'https://raw.githubusercontent.com/nitinpokharna/ansible-azure-lab/master/azuredeploy.parameters.json'
    # No parameters required for this template
    #paramsLink: ''
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: 'RG_TestVM1'
        # location seems to be not optional
        location: 'Southeast Asia'
        template_link: '{{ templateLink }}'
        #parameters_link: '{{ paramsLink }}'
        parameters:
          adminUsername:
              value: "testadmin"
          adminPassword:
              value: "Pass@1234567"
          numberOfInstances:
              value: 3
          location:
              value: "southeastasia"
          OS:
              value: "Windows"