---
- name: Start and Stop VMs
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    resourcegroupname: 'RG_DSC_IIS'
    location: 'southeastasia'
    vm_names_list:
     - "MyWindowsVM"
     - "TestVM1"
  tasks:
  - name: AZ Login to Azure
    shell: >
          az login --service-principal
          -u "3811c341-3877-4b3d-8f6c-265d042063c4"
          -p "upbGF8WaT94J6LZ++kQPjRpXvOOXv3pXoHHNytk0QDU="
          --tenant "ebed6f03-43f8-4b70-849d-514d19035401" && az account set --subscription "9da2f657-6c84-415a-8549-95c505c03f1b"
          #become: true

  - name: Start and Stop VMs
    with_items:
        - "{{ vm_names_list }}"
    shell: |
          
          az vm start -g "{{ resourcegroupname }}" -n "{{ vm_names_list }}"
          #az vm start -g "{{ resourcegroupname }}" -n "{{ vm_names_list }}"
          #az vm deallocate -g "{{ resourcegroupname }}" -n "{{ vm_names_list }}"
          #become: true